development:
  adapter: postgresql
  encoding: unicode
  database: sheql_dev
  pool: 2
  username:
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: sheql_prod
  pool: 2
  username:
  password:
